version: "3.8"
services:
  guestbook:
    build: .
    container_name: guestbook
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      # Mount a named volume at /data so that the database file (configured in .env) persists
      - /home/steve/kiosk-guestbook:/data

volumes:
  guestbook_data:
